import data_processing as dp

print(dp.cities_data[:10])
print()
print(dp.countries_data[:10])
print()
print(dp.teams_data[:10])
print()
print(dp.players_data[:10])
print()
print(dp.titanic_data[:10])
print()
print(dp.min_max_temp(dp.cities_data))
print()
print(dp.country_list(dp.cities_data))
print()
print(dp.average_country_temp(dp.cities_data))

# your test code for other data_processing functions

print()
print(dp.country_max_diff_temperature(dp.cities_data))
print()
print(dp.northern_southern_most_cities(dp.cities_data))
print()
print(dp.population_countries_no_coastline_in_EU(dp.countries_data))
print()
print(dp.cities_in_EU(dp.cities_data, dp.countries_data))
print()
print(dp.average_EU_city_temperature(dp.cities_data, dp.countries_data))
print()
print(dp.average_passes(dp.players_data))
print()
print(dp.max_GF_GA_ratio(dp.teams_data))
print()
print(dp.whose_player_list(dp.players_data, dp.teams_data))
print()
print(dp.team_list_passes_per_minute(dp.players_data, dp.teams_data))
print()
print(dp.number_married_women_embarked('Southampton', 30, dp.titanic_data))
print(dp.number_married_women_embarked('Queenstown', 34, dp.titanic_data))
print(dp.number_married_women_embarked('Cherbourg', 40, dp.titanic_data))
print(dp.number_married_women_embarked('Queenstown', 28, dp.titanic_data))
print(dp.number_married_women_embarked('Southampton', 42, dp.titanic_data))
print()
print(dp.class_survival_rate(1, dp.titanic_data))
print(dp.class_survival_rate(2, dp.titanic_data))
print(dp.class_survival_rate(3, dp.titanic_data))
print()
print(dp.gender_survival_number('M', dp.titanic_data))
print(dp.gender_survival_number('F', dp.titanic_data))
print()
print(dp.twin_list(dp.titanic_data))
